name: Receive pull request

on:
  pull_request:

jobs:
  lint:
    runs-on: ubuntu-20.04

    steps:
      - uses: actions/checkout@v3
      - uses: terraform-linters/setup-tflint@v2
        name: Setting up TFLint
        with:
          tflint_version: v0.29.0
      - name: Initializing TFLint
        run: tflint --init
      - name: Linting
        run: tflint -f compact --disable-rule=terraform_module_pinned_source

  qa:
    runs-on: ubuntu-20.04

    steps:
      - uses: actions/checkout@v3
      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v2.0.3
      - name: Terraform Format
        run: terraform fmt -check -recursive

  security-scan:
    runs-on: ubuntu-20.04

    steps:
      - uses: actions/checkout@v3
      - run: docker run -v ${PWD}:/src aquasec/tfsec:v1.8 /src
